### ISSUE TITLE
ISSUE: 2023-01-09 17:36:20.353 WARNING (SyncWorker_3) [custom_components.mail_and_packages.helpers] Unexpected html format found.

### ISSUE THREAD

**Issue by NeoFax75** [moralmunky/Home-Assistant-Mail-And-Packages#788] opened 2023-01-09 22:44 UTC
**Describe the bug**
2023-01-09 17:36:20.353 WARNING (SyncWorker_3) [custom_components.mail_and_packages.helpers] Unexpected html format found.

**Environment (please complete the following information):**
 - OS: HassOS
 - ProxMox NUC
 - Home Assistant version: 2023.01.01
 - Hassio 
 - Component version: 0.3.6

**Logs**
```
2023-01-09 14:13:33.111 WARNING (SyncWorker_1) [custom_components.mail_and_packages.helpers] Unexpected html format found.
2023-01-09 14:18:45.337 WARNING (SyncWorker_23) [custom_components.mail_and_packages.helpers] Unexpected html format found.
2023-01-09 14:23:57.384 WARNING (SyncWorker_16) [custom_components.mail_and_packages.helpers] Unexpected html format found.
2023-01-09 14:29:09.583 WARNING (SyncWorker_19) [custom_components.mail_and_packages.helpers] Unexpected html format found.
2023-01-09 14:34:21.984 WARNING (SyncWorker_2) [custom_components.mail_and_packages.helpers] Unexpected html format found.
2023-01-09 14:39:33.220 WARNING (SyncWorker_5) [custom_components.mail_and_packages.helpers] Unexpected html format found.
2023-01-09 14:44:45.556 WARNING (SyncWorker_3) [custom_components.mail_and_packages.helpers] Unexpected html format found.
2023-01-09 14:49:57.726 WARNING (SyncWorker_6) [custom_components.mail_and_packages.helpers] Unexpected html format found.
2023-01-09 14:55:09.321 WARNING (SyncWorker_3) [custom_components.mail_and_packages.helpers] Unexpected html format found.
2023-01-09 15:00:21.651 WARNING (SyncWorker_24) [custom_components.mail_and_packages.helpers] Unexpected html format found.
2023-01-09 15:05:33.058 WARNING (SyncWorker_11) [custom_components.mail_and_packages.helpers] Unexpected html format found.
2023-01-09 15:10:45.597 WARNING (SyncWorker_0) [custom_components.mail_and_packages.helpers] Unexpected html format found.
2023-01-09 15:15:57.868 WARNING (SyncWorker_13) [custom_components.mail_and_packages.helpers] Unexpected html format found.
2023-01-09 15:21:09.840 WARNING (SyncWorker_10) [custom_components.mail_and_packages.helpers] Unexpected html format found.
2023-01-09 15:26:21.435 WARNING (SyncWorker_4) [custom_components.mail_and_packages.helpers] Unexpected html format found.
2023-01-09 15:31:33.472 WARNING (SyncWorker_9) [custom_components.mail_and_packages.helpers] Unexpected html format found.
2023-01-09 15:36:45.245 WARNING (SyncWorker_14) [custom_components.mail_and_packages.helpers] Unexpected html format found.
2023-01-09 15:41:57.475 WARNING (SyncWorker_1) [custom_components.mail_and_packages.helpers] Unexpected html format found.
2023-01-09 15:47:09.106 WARNING (SyncWorker_3) [custom_components.mail_and_packages.helpers] Unexpected html format found.
2023-01-09 15:52:22.003 WARNING (SyncWorker_3) [custom_components.mail_and_packages.helpers] Unexpected html format found.
2023-01-09 15:57:34.651 WARNING (SyncWorker_5) [custom_components.mail_and_packages.helpers] Unexpected html format found.
2023-01-09 16:02:46.533 WARNING (SyncWorker_19) [custom_components.mail_and_packages.helpers] Unexpected html format found.
2023-01-09 16:07:58.280 WARNING (SyncWorker_24) [custom_components.mail_and_packages.helpers] Unexpected html format found.
2023-01-09 16:13:10.361 WARNING (SyncWorker_15) [custom_components.mail_and_packages.helpers] Unexpected html format found.
2023-01-09 16:18:22.703 WARNING (SyncWorker_7) [custom_components.mail_and_packages.helpers] Unexpected html format found.
2023-01-09 16:23:33.974 WARNING (SyncWorker_2) [custom_components.mail_and_packages.helpers] Unexpected html format found.
2023-01-09 16:28:46.185 WARNING (SyncWorker_0) [custom_components.mail_and_packages.helpers] Unexpected html format found.
2023-01-09 16:33:58.215 WARNING (SyncWorker_3) [custom_components.mail_and_packages.helpers] Unexpected html format found.
2023-01-09 16:39:09.936 WARNING (SyncWorker_6) [custom_components.mail_and_packages.helpers] Unexpected html format found.
2023-01-09 16:44:20.893 WARNING (SyncWorker_4) [custom_components.mail_and_packages.helpers] Unexpected html format found.
2023-01-09 16:49:32.552 WARNING (SyncWorker_4) [custom_components.mail_and_packages.helpers] Unexpected html format found.
2023-01-09 16:54:44.368 WARNING (SyncWorker_19) [custom_components.mail_and_packages.helpers] Unexpected html format found.
2023-01-09 16:59:56.593 WARNING (SyncWorker_8) [custom_components.mail_and_packages.helpers] Unexpected html format found.
2023-01-09 17:05:08.394 WARNING (SyncWorker_2) [custom_components.mail_and_packages.helpers] Unexpected html format found.
2023-01-09 17:10:20.725 WARNING (SyncWorker_18) [custom_components.mail_and_packages.helpers] Unexpected html format found.
2023-01-09 17:15:31.717 WARNING (MainThread) [custom_components.mail_and_packages.camera] Could not read camera Mail USPS Camera image from file: /config/custom_components/mail_and_packages/images/fd8b9f83-4078-4338-9ccf-b5c634d0cfc6.gif
2023-01-09 17:15:31.860 WARNING (SyncWorker_24) [custom_components.mail_and_packages.helpers] Unexpected html format found.
2023-01-09 17:20:44.255 WARNING (SyncWorker_17) [custom_components.mail_and_packages.helpers] Unexpected html format found.
2023-01-09 17:25:56.494 WARNING (SyncWorker_2) [custom_components.mail_and_packages.helpers] Unexpected html format found.
2023-01-09 17:31:08.562 WARNING (SyncWorker_19) [custom_components.mail_and_packages.helpers] Unexpected html format found.
```

**Comment by raetha** [comment] 2023-01-21 19:45
I'm seeing this same issue, though possibly not with the same frequency. Has anyone figured out a workaround or resolution?

**Comment by firstof9** [comment] 2023-01-21 21:30
Dupe of #771

**Comment by firstof9** [comment] 2023-01-21 21:30
The log level of the message will be changed. It is not an error.

**Closed by firstof9** 2023-01-21 21:30 UTC
Labels: duplicate, no-issue-activity
