### ISSUE TITLE
Unable to Setup

### ISSUE THREAD

**Issue by codypet** [moralmunky/Home-Assistant-Mail-And-Packages#68] opened 2020-03-18 20:03 UTC
I've been using an old version of this card from about 6 months ago which had been working decently fine all this time.  With 0.107 the card no longer worked so I thought it would be good to move to the current HACS configuration.

I'm getting the error below. 

> Logger: homeassistant.setup
> Source: setup.py:245
> First occurred: 3:40:24 PM (1 occurrences)
> Last logged: 3:40:24 PM
> 
> Unable to prepare setup for platform mail_and_packages.sensor: Platform not found ( IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE! Importing the numpy c-extensions failed. - Try uninstalling and reinstalling numpy. - If you have already done that, then: 1. Check that you expected to use Python3.7 from "/srv/homeassistant/bin/python", and that you have no directories in your PATH or PYTHONPATH that can interfere with the Python and numpy version "1.18.2" you're trying to use. 2. If (1) looks fine, you can open a new issue at https://github.com/numpy/numpy/issues. Please include details on: - how you installed Python - how you installed numpy - your operating system - whether or not you have multiple versions of Python installed - if you built from source, your compiler versions and ideally a build log - If you're working with a numpy git repository, try `git clean -xdf` (removes all files not under version control) and rebuild numpy. Note: this error has many possible causes, so please don't comment on an existing issue about this - open a new one instead. Original error was: libf77blas.so.3: cannot open shared object file: No such file or directory ).

> Logger: homeassistant.components.local_file.camera
> Source: components/local_file/camera.py:44
> Integration: local_file (documentation, issues)
> First occurred: 3:40:22 PM (1 occurrences)
> Last logged: 3:40:22 PM
> 
> Could not read camera mail_usps image from file: /config/www/mail_and_packages/mail_today.gif

 Also I notice the documentation no longer has the old lovelace card that looked like an envelope.  Is that no longer available?

**Comment by moralmunky** [comment] 2020-03-18 20:21
Duplicate of #63. You are on a raspberry pi, right?

**Comment by moralmunky** [comment] 2020-03-18 20:22
Also the card was separated from the integration. 

https://github.com/moralmunky/Home-Assistant-Mail-And-Packages-Custom-Card

**Comment by codypet** [comment] 2020-03-19 00:03
> Duplicate of #63. You are on a raspberry pi, right?
Yes in Venv


> Also the card was separated from the integration.
> 
> https://github.com/moralmunky/Home-Assistant-Mail-And-Packages-Custom-Card
Ah!  Thank you.

**Comment by firstof9** [comment] 2020-03-19 01:02
Give it a ```sudo apt-get install libatlas-base-dev```  see if that resolves the numpy issue for you.

**Comment by codypet** [comment] 2020-03-19 12:45
Ah!  Thank you.  I don't see the photos but I do see I have four pieces of mail.

**Closed** 2020-03-20 02:57 UTC
