### ISSUE TITLE
ISSUE: Amazon Delivered Was Removed?

### ISSUE THREAD

**Issue by ThatGuy9811** [moralmunky/Home-Assistant-Mail-And-Packages#272] opened 2020-12-01 23:18 UTC
**Describe the bug**

**Environment (please complete the following information):**
 - OS: [e.g. HassOS/Raspbian/CentOS]
 - Type of device: [e.g. RPi3/NUC/Synology]
 - Home Assistant version: [e.g. 0.105.5]
 - Hassio/Docker/Core? 
 - Component version: [e.g. 0.1.2]

**Logs**
Paste your error logs here.

**Screenshots**

**Additional context**
Please add emails in plain/text format if possible and applicable.

**Comment by firstof9** [comment] 2020-12-01 23:28
Dupe of #260

**Closed by firstof9** 2020-12-01 23:28 UTC
Labels: duplicate
