### ISSUE TITLE
ISSUE: USPS packages sensor not working

### ISSUE THREAD

**Issue by Noob25930** [moralmunky/Home-Assistant-Mail-And-Packages#638] opened 2022-02-28 18:25 UTC
Mail and package not updating USPS PACKAGE sensor despite tracking information in the "Daily Digest"

**Environment (please complete the following information):**
 - OS: [HassOS]
 - Type of device: [VM]

On There Way should show two packages on the blue icon USPS
![2022-02-28 (3)](https://user-images.githubusercontent.com/97673068/156037888-278b38ff-7324-419a-b70d-2ab49446c217.png)
The actual email in my inbox
![Inked2022-02-28](https://user-images.githubusercontent.com/97673068/156037044-897b46d1-0395-4313-b0e0-f3b3164433c6.jpg)

**Additional context**
I also tried to change some numbers in the sensor itself. Was not sure totally what I was doing but tried to see if adding 678 in the following would help but to it did not. {"pattern": ["9[2345678]\\d{15,26}"]}

![Inked2022-02-28 (2)](https://user-images.githubusercontent.com/97673068/156037419-3cd42edc-f09b-4159-9a2a-a81c87ac3c76.jpg)

**Comment by firstof9** [comment] 2022-02-28 18:51
Dupe of #636

**Comment by Noob25930** [comment] 2022-02-28 19:04
Thank you. I understand.

**Closed** 2022-02-28 21:29 UTC
Labels: duplicate
