### ISSUE TITLE
Mail gif assumes shape of first mail piece

### ISSUE THREAD

**Issue by moralmunky** [moralmunky/Home-Assistant-Mail-And-Packages#32] opened 2020-02-15 03:28 UTC
The mail I received today started with a square image and all subsequent rectangular images filled canvas area cutting off the left and right side. 

I had solved for this previously by resizing all the images proportionately within 700x315. I think this matched the no mail image. When assembling the gif the background was filled with white so you wouldn't see the outside parts of the pervious image if it was larger than the new image.

For reference:
`IMG_RESIZE_OPTIONS = ('convert -resize 700x315 ')
GIF_MAKER_OPTIONS = ('convert -delay 300 -loop 0 -coalesce -fill white '
                     '-dispose Background ')`

**Comment by firstof9** [comment] 2020-02-17 16:42
Currently working on this ;)

**Comment by firstof9** [comment] 2020-02-18 01:43
Pushed a commit on my fork @moralmunky if you want to test it _should_ resize the images to 700x315

**Comment by moralmunky** [comment] 2020-02-20 14:32
Looks like we have it fitting the images in the specified dimension, no containt on aspect ratio. Is that that intention? If so, I can confirm it's working. Does it do this in memory? I don't see the change on the individual files on the disk. No real need to see it in the image files saved out, just curious.

**Comment by firstof9** [comment] 2020-02-20 15:34
> Looks like we have it fitting the images in the specified dimension, no containt on aspect ratio. Is that that intention? If so, I can confirm it's working.

Ya I'm still looking into keeping the ratio with the scikit-image package.

> Does it do this in memory?
The resizing is done on the numpy array the images are read into, so basically in memory. I found it a pretty decent solution to not having to rely on Imagemagick

**Comment by firstof9** [comment] 2020-02-20 16:40
@moralmunky latest commit _should_ resolve the aspect ratio

**Comment by moralmunky** [comment] 2020-02-22 22:26
Reopening and working it though on the [image-resize branch](https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/tree/image-resize)

Images are sized within the 315 x 700 bounds but when stitching together the gif, the first image which now has the size of w:660h:315 becomes the size of the gif.

Two options I can think of now:
1. Find how skimage can add blank pixels to make all the images exactly 315 x 700 after they are sized to fit within that size.
2. Add a template image that is 315 x 700 to always be the first image of the array so the gif always takes on the right size. It could say 'mail today' or something so it's not just a blank slide.

I also found this
https://jdhao.github.io/2017/11/06/resize-image-to-square-with-padding/

**Comment by firstof9** [comment] 2020-02-23 15:30
Looks like it can pad the image using 'mode=median'
So a ```resize(image, (height, width), mode='median')``` may resolve the issue.
The different modes to try are listed here: https://docs.scipy.org/doc/numpy/reference/generated/numpy.pad.html#numpy.pad

**Comment by firstof9** [comment] 2020-02-25 02:54
I have confirmed that ```resize(image, (317, 700), mode='symmetric')``` an image too tall and compacted it down, still readable. Waiting on a image too small in width to see how it reacts.

**Comment by firstof9** [comment] 2020-06-18 22:17
Ok this seems fixed in the latest beta, at least for me.

**Closed** 2020-06-23 02:26 UTC
Labels: bug, enhancement
