### ISSUE TITLE
WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.mail_image_system_path (<class 'custom_components.mail_and_packages.sensor.ImagePathSensors'>) implements device_state_attributes.

### ISSUE THREAD

**Issue by niemyjski** [moralmunky/Home-Assistant-Mail-And-Packages#649] opened 2022-04-01 18:10 UTC
**Describe the bug**

WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.mail_image_system_path (<class 'custom_components.mail_and_packages.sensor.ImagePathSensors'>) implements device_state_attributes. Please report it to the custom component author.

**Environment (please complete the following information):**
 - OS: [e.g. HassOS/Raspbian/CentOS] HassOS
 - Type of device: [e.g. RPi3/NUC/Synology] NUC
 - Home Assistant version: [e.g. 0.105.5] 2022.3.8
 - Hassio/Docker/Core?  Hassio
 - Component version: [e.g. 0.1.2] latest

**Logs**

```
2022-04-01 13:06:02 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.mail_ups_packages (<class 'custom_components.mail_and_packages.sensor.PackagesSensor'>) implements device_state_attributes. Please report it to the custom component author.
2022-04-01 13:06:02 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.mail_usps_delivered (<class 'custom_components.mail_and_packages.sensor.PackagesSensor'>) implements device_state_attributes. Please report it to the custom component author.
2022-04-01 13:06:02 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.mail_usps_delivering (<class 'custom_components.mail_and_packages.sensor.PackagesSensor'>) implements device_state_attributes. Please report it to the custom component author.
2022-04-01 13:06:02 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.mail_usps_mail (<class 'custom_components.mail_and_packages.sensor.PackagesSensor'>) implements device_state_attributes. Please report it to the custom component author.
2022-04-01 13:06:02 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.mail_usps_packages (<class 'custom_components.mail_and_packages.sensor.PackagesSensor'>) implements device_state_attributes. Please report it to the custom component author.
2022-04-01 13:06:02 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.mail_packages_delivered (<class 'custom_components.mail_and_packages.sensor.PackagesSensor'>) implements device_state_attributes. Please report it to the custom component author.
2022-04-01 13:06:02 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.mail_packages_in_transit (<class 'custom_components.mail_and_packages.sensor.PackagesSensor'>) implements device_state_attributes. Please report it to the custom component author.
2022-04-01 13:06:02 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.mail_image_system_path (<class 'custom_components.mail_and_packages.sensor.ImagePathSensors'>) implements device_state_attributes. Please report it to the custom component author.
2022-04-01 13:06:02 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.mail_image_url (<class 'custom_components.mail_and_packages.sensor.ImagePathSensors'>) implements device_state_attributes. Please report it to the custom component author.
2022-04-01 13:06:02 WARNING (SyncWorker_4) [homeassistant.components.local_file.camera] Could not read camera mail_usps image from file: /custom_components/mail_and_packages/mail_none.gif
```

**Screenshots**

**Additional context**
Please add emails in plain/text format if possible and applicable.

**Comment by firstof9** [comment] 2022-04-01 19:33
Dupe of #603 

Already fixed in beta versions.

**Closed by firstof9** 2022-04-01 19:33 UTC
Labels: duplicate
