### ISSUE TITLE
ISSUE: Invalid date format amazon.de

### ISSUE THREAD

**Issue by fwmarcel** [moralmunky/Home-Assistant-Mail-And-Packages#860] opened 2023-10-26 18:09 UTC
**Describe the bug**
I am having problems evaluating shipping emails from Amazon. In the log I see that the date from the mail is not evaluated correctly. Accordingly, I see unfortunately no counter for the packages. If more information is needed, I will be happy to add it.

**Environment (please complete the following information):**
 - OS: HassOS
 - Type of device: Rpi4
 - Home Assistant version: 2023.10.5
 - Hassio
 - Component version: 0.3.19

**Logs**
```
2023-10-26 19:22:15.127 DEBUG (SyncWorker_13) [custom_components.mail_and_packages.helpers] Invalid date format found for language de_DE.UTF-8. (time data '13 Oktober\n\n\nDie' does not match format '%d %B')
2023-10-26 19:22:15.127 DEBUG (SyncWorker_13) [custom_components.mail_and_packages.helpers] Arrive Date: Freitag, 13 Oktober

2023-10-26 19:22:15.186 DEBUG (SyncWorker_13) [custom_components.mail_and_packages.helpers] Arrive Date: Freitag, 27 Oktober
2023-10-26 19:22:15.188 DEBUG (SyncWorker_13) [custom_components.mail_and_packages.helpers] Invalid date format found for language de_DE. (time data '27 Oktober' does not match format '%d %B')
2023-10-26 19:22:15.188 DEBUG (SyncWorker_13) [custom_components.mail_and_packages.helpers] Arrive Date: Freitag, 27 Oktober
2023-10-26 19:22:15.189 DEBUG (SyncWorker_13) [custom_components.mail_and_packages.helpers] Invalid date format found for language de_DE.UTF-8. (time data '27 Oktober' does not match format '%d %B')
```

**Screenshots**
<img width="314" alt="image" src="https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/assets/22275913/401dd09b-4dcc-406b-b7d4-083b5268fe77">

**Comment by firstof9** [comment] 2023-10-26 18:12
duplicate of #751

**Closed** 2023-11-11 02:39 UTC
Labels: duplicate, no-issue-activity
