### ISSUE TITLE
ISSUE: Failing to Parse Non-Multipart Message

### ISSUE THREAD

**Issue by Silvenga** [moralmunky/Home-Assistant-Mail-And-Packages#118] opened 2020-05-12 22:49 UTC
**Describe the bug**
When attempting to load the component, some email messages appear to prevent initialization with the below stacktrace.

**Environment:**
 - OS: Ubuntu 18.04
 - Type of device: Generic Linux
 - Home Assistant version: `0.109.6`
 - Hassio/Docker/Core? Hassio via generic linux
 - Component version: `master` and `1.5`

**Logs**
```
2020-05-12 17:21:46 INFO (MainThread) [homeassistant.components.sensor] Setting up sensor.mail_and_packages
2020-05-12 17:21:46 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Config scan interval: 0:05:00
2020-05-12 17:21:47 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Attempting to find Informed Delivery mail
2020-05-12 17:21:47 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Cleaning up image directory: /config/images/mail_and_packages/
2020-05-12 17:21:47 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Informed Delivery email found processing...
2020-05-12 17:21:47 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Removing duplicate images.
2020-05-12 17:21:47 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Removing USPS announcement images.
2020-05-12 17:21:47 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Image Count: 0
2020-05-12 17:21:47 INFO (MainThread) [custom_components.mail_and_packages.sensor] No mail found.
2020-05-12 17:21:47 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Copying nomail gif
2020-05-12 17:21:47 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Attempting to find mail from auto-reply@usps.com with subject 1 Item Delivered
2020-05-12 17:21:47 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Found from auto-reply@usps.com with subject 1 Item Delivered, b''
2020-05-12 17:21:47 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Attempting to find mail from auto-reply@usps.com with subject 1 Expected Delivery on
2020-05-12 17:21:47 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Found from auto-reply@usps.com with subject 1 Expected Delivery on, b''
2020-05-12 17:21:47 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Attempting to find mail from mcinfo@ups.com with subject 1 Your UPS Package was delivered
2020-05-12 17:21:47 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Found from mcinfo@ups.com with subject 1 Your UPS Package was delivered, b''
2020-05-12 17:21:47 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Attempting to find mail from mcinfo@ups.com with subject 1 UPS Update: Package Scheduled for Delivery Today
2020-05-12 17:21:47 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Found from mcinfo@ups.com with subject 1 UPS Update: Package Scheduled for Delivery Today, b''
2020-05-12 17:21:47 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Attempting to find mail from mcinfo@ups.com with subject 2 UPS Update: Follow Your Delivery on a Live Map
2020-05-12 17:21:47 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Found from mcinfo@ups.com with subject 2 UPS Update: Follow Your Delivery on a Live Map, b''
2020-05-12 17:21:47 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Attempting to find mail from TrackingUpdates@fedex.com with subject 1 Your package has been delivered
2020-05-12 17:21:47 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Found from TrackingUpdates@fedex.com with subject 1 Your package has been delivered, b''
2020-05-12 17:21:47 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Attempting to find mail from TrackingUpdates@fedex.com with subject 1 Delivery scheduled for today
2020-05-12 17:21:47 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Found from TrackingUpdates@fedex.com with subject 1 Delivery scheduled for today, b''
2020-05-12 17:21:47 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Attempting to find mail from TrackingUpdates@fedex.com with subject 2 Your package is scheduled for delivery today
2020-05-12 17:21:47 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Found from TrackingUpdates@fedex.com with subject 2 Your package is scheduled for delivery today, b''
2020-05-12 17:21:47 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Attempting to find Amazon email with item list ...
2020-05-12 17:21:47 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Amazon emails found: 3
2020-05-12 17:21:48 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up mail_and_packages platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 178, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/config/custom_components/mail_and_packages/sensor.py", line 146, in async_setup_entry
    sensors.append(PackagesSensor(data, variable))
  File "/config/custom_components/mail_and_packages/sensor.py", line 261, in __init__
    self.update()
  File "/config/custom_components/mail_and_packages/sensor.py", line 309, in update
    self.data.update()
  File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 240, in wrapper
    result = method(*args, **kwargs)
  File "/config/custom_components/mail_and_packages/sensor.py", line 201, in update
    count[sensor] = get_items(account, "count")
  File "/config/custom_components/mail_and_packages/sensor.py", line 622, in get_items
    email_msg = str(msg.get_payload(0))
  File "/usr/local/lib/python3.7/email/message.py", line 257, in get_payload
    raise TypeError('Expected list, got %s' % type(self._payload))
TypeError: Expected list, got <class 'str'>
```

**Additional context**
This is a Office 365 (Exchange Online via IMAP) account, which should be close to a Outlook Online account. Not sure if that would really matter.

The error screams this issue (https://stackoverflow.com/questions/1463074/how-can-i-get-an-email-messages-text-content-using-python) - but I'm no Python developer. The emails appear to be multi-part, removing the emails does allow the component to load. I'm having troubling dumping the raw message, since Outlook likes to hide the complexities of mime.

**Comment by firstof9** [comment] 2020-05-13 00:02
Duplicate of #106 this is fixed in the latest beta if you'd care to give it a go.

**Comment by Silvenga** [comment] 2020-05-13 00:51
I should have checked the betas, sorry about that.

I swapped over to `0.2.0-b6`, the issue appears to be still present.

```
2020-05-12 19:48:44 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Config scan interval: 0:05:00
2020-05-12 19:48:45 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Attempting to find Informed Delivery mail
2020-05-12 19:48:45 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Cleaning up image directory: /config/images/mail_and_packages/
2020-05-12 19:48:45 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Informed Delivery email found processing...
2020-05-12 19:48:45 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Removing duplicate images.
2020-05-12 19:48:45 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Removing USPS announcement images.
2020-05-12 19:48:45 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Image Count: 0
2020-05-12 19:48:45 INFO (MainThread) [custom_components.mail_and_packages.sensor] No mail found.
2020-05-12 19:48:45 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Copying nomail gif
2020-05-12 19:48:45 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Attempting to find mail from auto-reply@usps.com with subject 1 Item Delivered
2020-05-12 19:48:45 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Found from auto-reply@usps.com with subject 1 Item Delivered, b''
2020-05-12 19:48:45 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Attempting to find mail from auto-reply@usps.com with subject 1 Expected Delivery on
2020-05-12 19:48:45 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Searching for out for delivery in emails
2020-05-12 19:48:45 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Found from auto-reply@usps.com with subject 1 Expected Delivery on, b''
2020-05-12 19:48:45 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Attempting to find mail from mcinfo@ups.com with subject 1 Your UPS Package was delivered
2020-05-12 19:48:45 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Found from mcinfo@ups.com with subject 1 Your UPS Package was delivered, b''
2020-05-12 19:48:45 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Attempting to find mail from mcinfo@ups.com with subject 1 UPS Update: Package Scheduled for Delivery Today
2020-05-12 19:48:45 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Found from mcinfo@ups.com with subject 1 UPS Update: Package Scheduled for Delivery Today, b''
2020-05-12 19:48:45 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Attempting to find mail from mcinfo@ups.com with subject 2 UPS Update: Follow Your Delivery on a Live Map
2020-05-12 19:48:45 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Found from mcinfo@ups.com with subject 2 UPS Update: Follow Your Delivery on a Live Map, b''
2020-05-12 19:48:45 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Attempting to find mail from TrackingUpdates@fedex.com with subject 1 Your package has been delivered
2020-05-12 19:48:45 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Found from TrackingUpdates@fedex.com with subject 1 Your package has been delivered, b''
2020-05-12 19:48:45 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Attempting to find mail from TrackingUpdates@fedex.com with subject 1 Delivery scheduled for today
2020-05-12 19:48:45 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Found from TrackingUpdates@fedex.com with subject 1 Delivery scheduled for today, b''
2020-05-12 19:48:45 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Attempting to find mail from TrackingUpdates@fedex.com with subject 2 Your package is scheduled for delivery today
2020-05-12 19:48:45 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Found from TrackingUpdates@fedex.com with subject 2 Your package is scheduled for delivery today, b''
2020-05-12 19:48:45 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Attempting to find Amazon email with item list ...
2020-05-12 19:48:45 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Amazon emails found: 2
2020-05-12 19:48:45 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up mail_and_packages platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 178, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/config/custom_components/mail_and_packages/sensor.py", line 150, in async_setup_entry
    sensors.append(PackagesSensor(data, variable))
  File "/config/custom_components/mail_and_packages/sensor.py", line 265, in __init__
    self.update()
  File "/config/custom_components/mail_and_packages/sensor.py", line 313, in update
    self.data.update()
  File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 240, in wrapper
    result = method(*args, **kwargs)
  File "/config/custom_components/mail_and_packages/sensor.py", line 205, in update
    count[sensor] = get_items(account, "count")
  File "/config/custom_components/mail_and_packages/sensor.py", line 668, in get_items
    email_msg = str(msg.get_payload(0))
  File "/usr/local/lib/python3.7/email/message.py", line 257, in get_payload
    raise TypeError('Expected list, got %s' % type(self._payload))
TypeError: Expected list, got <class 'str'>
```

**Comment by firstof9** [comment] 2020-05-13 13:27
Are these 2 emails the "Your order #xxxxxxxxxxx has shipped" emails?

**Comment by firstof9** [comment] 2020-05-13 15:30
Give this tweak a try:
https://raw.githubusercontent.com/firstof9/Home-Assistant-Mail-And-Packages/condense-sensor/custom_components/mail_and_packages/sensor.py

Just replace the file.

**Comment by firstof9** [comment] 2020-05-13 19:53
Posted it to 0.2.0-b7, should fix you up.

**Comment by Silvenga** [comment] 2020-05-13 22:28
I updated to `0.2.0-b7`, unfortunately the component is still continuing to fail during setup:

```
2020-05-13 17:25:26 INFO (MainThread) [homeassistant.components.sensor] Setting up sensor.mail_and_packages
2020-05-13 17:25:26 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Config scan interval: 0:05:00
2020-05-13 17:25:27 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Attempting to find Informed Delivery mail
2020-05-13 17:25:27 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Cleaning up image directory: /config/images/mail_and_packages/
2020-05-13 17:25:27 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Informed Delivery email found processing...
2020-05-13 17:25:27 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Removing duplicate images.
2020-05-13 17:25:27 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Removing USPS announcement images.
2020-05-13 17:25:27 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Image Count: 0
2020-05-13 17:25:27 INFO (MainThread) [custom_components.mail_and_packages.sensor] No mail found.
2020-05-13 17:25:27 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Copying nomail gif
2020-05-13 17:25:27 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Attempting to find mail from auto-reply@usps.com with subject 1 Item Delivered
2020-05-13 17:25:27 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Found from auto-reply@usps.com with subject 1 Item Delivered, b''
2020-05-13 17:25:27 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Attempting to find mail from auto-reply@usps.com with subject 1 Expected Delivery on
2020-05-13 17:25:27 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Searching for out for delivery in emails
2020-05-13 17:25:27 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Found from auto-reply@usps.com with subject 1 Expected Delivery on, b''
2020-05-13 17:25:27 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Attempting to find mail from mcinfo@ups.com with subject 1 Your UPS Package was delivered
2020-05-13 17:25:27 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Found from mcinfo@ups.com with subject 1 Your UPS Package was delivered, b''
2020-05-13 17:25:27 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Attempting to find mail from mcinfo@ups.com with subject 1 UPS Update: Package Scheduled for Delivery Today
2020-05-13 17:25:27 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Found from mcinfo@ups.com with subject 1 UPS Update: Package Scheduled for Delivery Today, b''
2020-05-13 17:25:27 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Attempting to find mail from mcinfo@ups.com with subject 2 UPS Update: Follow Your Delivery on a Live Map
2020-05-13 17:25:27 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Found from mcinfo@ups.com with subject 2 UPS Update: Follow Your Delivery on a Live Map, b''
2020-05-13 17:25:27 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Attempting to find mail from TrackingUpdates@fedex.com with subject 1 Your package has been delivered
2020-05-13 17:25:27 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Found from TrackingUpdates@fedex.com with subject 1 Your package has been delivered, b''
2020-05-13 17:25:27 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Attempting to find mail from TrackingUpdates@fedex.com with subject 1 Delivery scheduled for today
2020-05-13 17:25:27 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Found from TrackingUpdates@fedex.com with subject 1 Delivery scheduled for today, b''
2020-05-13 17:25:27 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Attempting to find mail from TrackingUpdates@fedex.com with subject 2 Your package is scheduled for delivery today
2020-05-13 17:25:27 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Found from TrackingUpdates@fedex.com with subject 2 Your package is scheduled for delivery today, b''
2020-05-13 17:25:27 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Attempting to find Amazon email with item list ...
2020-05-13 17:25:28 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Amazon emails found: 4
2020-05-13 17:25:28 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up mail_and_packages platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 178, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/config/custom_components/mail_and_packages/sensor.py", line 150, in async_setup_entry
    sensors.append(PackagesSensor(data, variable))
  File "/config/custom_components/mail_and_packages/sensor.py", line 265, in __init__
    self.update()
  File "/config/custom_components/mail_and_packages/sensor.py", line 313, in update
    self.data.update()
  File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 240, in wrapper
    result = method(*args, **kwargs)
  File "/config/custom_components/mail_and_packages/sensor.py", line 205, in update
    count[sensor] = get_items(account, "count")
  File "/config/custom_components/mail_and_packages/sensor.py", line 668, in get_items
    email_msg = str(msg.get_payload(0))
  File "/usr/local/lib/python3.7/email/message.py", line 257, in get_payload
    raise TypeError('Expected list, got %s' % type(self._payload))
TypeError: Expected list, got <class 'str'>
```

**Comment by firstof9** [comment] 2020-05-13 22:41
Not all of them are the shipment notices are they?

**Comment by Silvenga** [comment] 2020-05-13 22:46
I deleted most of them to leave only the newest two - both are in the format of:

```
Your Amazon.com order #<order number> has shipped
```

**Comment by firstof9** [comment] 2020-05-13 23:01
Very strange I cannot duplicate that issue, I have 5 of those email right now all getting parsed fine.

I have added some try/catch to 0.2.0-b8 to stop it from causing the component not to load while I keep looking into this oddity.

I don't supose you have a way to check the raw message? It's been ages since I messed with outlook/hotmail/live email servers.

**Comment by Silvenga** [comment] 2020-05-13 23:05
Yeah, let me try to get the raw message. I'll try a different client.

**Comment by Silvenga** [comment] 2020-05-13 23:29
It does look like the emails I've received from Amazon are not multipart (looking at the raw envelope pulled directly over IMAP).

```
Content-Type: text/html; charset="utf-8"
Content-Transfer-Encoding: base64
```

Now I can't tell if Exchange is modifying the incoming emails - stripping text if html exists, or is Gmail modifying the incoming emails to be multipart. Or neither, is Amazon just sending me only html for some odd reason. Wouldn't be the first time my Amazon account did odd things that no other account did (e.g. getting a different login flow).

Although, I really wouldn't doubt Exchange Online is messing with something for some weird historical reason and there's some deep feature flag somewhere that disables this legacy behavior. I might as well open up a support ticket, because now I want to know. I read something about supporting Apple devices back in 2007 🤷.

I unfortunately don't have raw ingress logs, since my relays are managed by Exchange Online.

**Comment by firstof9** [comment] 2020-05-14 00:32
I'll keep looking into it, I have a backup plan if I can't find something more definite.

**Comment by Silvenga** [comment] 2020-05-14 23:31
It does not look like Exchange Online is modifying the message, I've requested a confirmation from support.

USPS messages, for example, are sent in multi-part with, two parts:

```
Content-Type: multipart/mixed;
Content-Type: text/plain
Content-Type: text/html
```

And, when downloading that message with IMAP, those two parts exist. When download with Outlook, these parts are modified (so it looks like Outlook is modifying the message, but that doesn't impact the message stored).

So, that makes me think that Amazon is only sending the message with:
```
Content-Type: text/html
```
And no further modification is being done. That said, I don't have access to the relay, so I really am just guessing what Amazon is sending. I'm assuming the message downloaded via IMAP is valid.

Does Amazon normally send multipart messages? Am I just going down the completely wrong path here?

**Comment by firstof9** [comment] 2020-05-15 13:51
Yup I get:
```
Content-Type: text/plain; charset=utf-8
Content-Transfer-Encoding: 7bit
```
and
```
Content-Type: text/html; charset=utf-8
Content-Transfer-Encoding: 7bit
```
We're only using the text/plain.

Give this a shot see if it does anything for you:
https://raw.githubusercontent.com/firstof9/Home-Assistant-Mail-And-Packages/condense-sensor/custom_components/mail_and_packages/sensor.py

**Comment by Silvenga** [comment] 2020-05-15 16:02
Looking back at my archive of Amazon emails (only shipping notices), it's odd. Two emails within 24 hours, same order ID (not sure why I received two notifications). The message id's were different, sent from different Amazon servers. The content is the same, just sent at different times.

```
1/27/2020 - Content-Type: multipart/alternative; 
1/28/2020 - Content-Type: text/html; charset="utf-8"
```

The headers on the different emails were different. For example, the first email had a DKIM-Signature, while the second did not. Throughout my email archive, since 12/2019, the emails switch back and forth from `multipart` to just `text/html` with all the notifications from this month being only `text/html`.

This makes me think, Amazon is slowly phasing in a new emailing implementation for their notifications.

**Comment by Silvenga** [comment] 2020-05-17 14:49
Tested your `condense-sensor` branch:

```
2020-05-17 09:36:35 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Config scan interval: 0:05:00
2020-05-17 09:36:36 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Attempting to find Informed Delivery mail
2020-05-17 09:36:36 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Cleaning up image directory: /config/images/mail_and_packages/
2020-05-17 09:36:36 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Informed Delivery email found processing...
2020-05-17 09:36:36 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Removing duplicate images.
2020-05-17 09:36:36 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Removing USPS announcement images.
2020-05-17 09:36:36 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Image Count: 0
2020-05-17 09:36:36 INFO (MainThread) [custom_components.mail_and_packages.sensor] No mail found.
2020-05-17 09:36:36 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Copying nomail gif
2020-05-17 09:36:36 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Attempting to find mail from auto-reply@usps.com with subject 1 Item Delivered
2020-05-17 09:36:36 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Found from auto-reply@usps.com with subject 1 Item Delivered, b''
2020-05-17 09:36:36 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Attempting to find mail from auto-reply@usps.com with subject 1 Expected Delivery on
2020-05-17 09:36:36 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Searching for out for delivery in emails
2020-05-17 09:36:36 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Found from auto-reply@usps.com with subject 1 Expected Delivery on, b''
2020-05-17 09:36:36 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Attempting to find mail from mcinfo@ups.com with subject 1 Your UPS Package was delivered
2020-05-17 09:36:36 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Found from mcinfo@ups.com with subject 1 Your UPS Package was delivered, b''
2020-05-17 09:36:36 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Attempting to find mail from mcinfo@ups.com with subject 1 UPS Update: Package Scheduled for Delivery Today
2020-05-17 09:36:36 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Found from mcinfo@ups.com with subject 1 UPS Update: Package Scheduled for Delivery Today, b''
2020-05-17 09:36:36 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Attempting to find mail from mcinfo@ups.com with subject 2 UPS Update: Follow Your Delivery on a Live Map
2020-05-17 09:36:36 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Found from mcinfo@ups.com with subject 2 UPS Update: Follow Your Delivery on a Live Map, b''
2020-05-17 09:36:36 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Attempting to find mail from TrackingUpdates@fedex.com with subject 1 Your package has been delivered
2020-05-17 09:36:36 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Found from TrackingUpdates@fedex.com with subject 1 Your package has been delivered, b''
2020-05-17 09:36:36 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Attempting to find mail from TrackingUpdates@fedex.com with subject 1 Delivery scheduled for today
2020-05-17 09:36:36 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Found from TrackingUpdates@fedex.com with subject 1 Delivery scheduled for today, b''
2020-05-17 09:36:36 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Attempting to find mail from TrackingUpdates@fedex.com with subject 2 Your package is scheduled for delivery today
2020-05-17 09:36:36 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Found from TrackingUpdates@fedex.com with subject 2 Your package is scheduled for delivery today, b''
2020-05-17 09:36:36 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Attempting to find Amazon email with item list ...
2020-05-17 09:36:36 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Amazon emails found: 1
2020-05-17 09:36:36 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Amazon skipped due to payload issues: Your Amazon.com order #114-1213078-7416266 has shipped
2020-05-17 09:36:36 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Error message: Expected list, got <class 'str'>
2020-05-17 09:36:36 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Amazon Count: 0
2020-05-17 09:36:36 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Attempting to find Amazon email with item list ...
2020-05-17 09:36:36 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Amazon emails found: 1
2020-05-17 09:36:36 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Amazon skipped due to payload issues: Your Amazon.com order #114-1213078-7416266 has shipped
2020-05-17 09:36:36 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Error message: Expected list, got <class 'str'>
2020-05-17 09:36:36 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Amazon order: []
2020-05-17 09:36:36 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Updated scan time: May-17-2020 09:36 AM
```

The component lives! Be without the Amazon sensor, but mostly working is much better then failing to initialize. 😹 

I think given the signature (are they called signatures? I need to learn Python):

`get_payload([i[, decode]])`

> With optional argument i, get_payload() will return the i-th element of the payload, counting from zero, if is_multipart() is True. An IndexError will be raised if i is less than 0 or greater than or equal to the number of items in the payload. If the payload is a string (i.e. is_multipart() is False) and i is given, a TypeError is raised.

It seems that invoked with a `i` argument when `is_multipart() == false` will always result in a TypeError.

That said, I wonder if the Amazon part of the component should completely ignore non-multipart Amazon emails (with a log message?), since the `arrive_date` parsing depends on plain text, to more or less protect the component from failing to initialize.

**Comment by firstof9** [comment] 2020-05-17 15:47
Ya the code I threw together is just a stop gap until I can put in the multipart check and throw an error in the log. Mostly we don't want errors halting the sensors from being created.

**Closed** 2020-05-20 00:19 UTC
Labels: duplicate, investigating
