### ISSUE TITLE
Entity sensor.mail_usps_packages (<class 'custom_components.mail_and_packages.sensor.PackagesSensor'>) implements device_state_attributes. Please report it to the custom component author.

### ISSUE THREAD

**Issue by acoreyj** [moralmunky/Home-Assistant-Mail-And-Packages#650] opened 2022-04-05 17:29 UTC
**Describe the bug**

**Environment (please complete the following information):**
 - OS:HassOS
 - Type of device: NUC
 - Home Assistant version: [e.g. core-2022.3.8]
 - Hassio
 - Component version: [
0.3.3-2
]

**Logs**
Logger: homeassistant.helpers.entity
Source: helpers/entity.py:601
First occurred: 12:23:16 PM (23 occurrences)
Last logged: 12:23:16 PM

Entity sensor.mail_usps_packages (<class 'custom_components.mail_and_packages.sensor.PackagesSensor'>) implements device_state_attributes. Please report it to the custom component author.
Entity sensor.mail_packages_delivered (<class 'custom_components.mail_and_packages.sensor.PackagesSensor'>) implements device_state_attributes. Please report it to the custom component author.
Entity sensor.mail_packages_in_transit (<class 'custom_components.mail_and_packages.sensor.PackagesSensor'>) implements device_state_attributes. Please report it to the custom component author.
Entity sensor.mail_image_system_path (<class 'custom_components.mail_and_packages.sensor.ImagePathSensors'>) implements device_state_attributes. Please report it to the custom component author.
Entity sensor.mail_image_url (<class 'custom_components.mail_and_packages.sensor.ImagePathSensors'>) implements device_state_attributes. Please report it to the custom component author.
**Screenshots**

**Additional context**
Doesn't seem to be working, not sure if this is the issue.

**Comment by firstof9** [comment] 2022-04-05 17:32
Dupe of #603 

Already fixed in beta versions, please use the latest beta version until the next release.

**Closed** 2022-04-05 18:50 UTC
Labels: duplicate
